# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 952a148d983ccc786923431ed0c959b7cd750b036ce2f54d8fb7cd26dcc387abb8fb37c31e09ef46da27610d48ab327279e81659f46ffd00fae11bc25a5a8649

test:
  secret_key_base: 5418c54f711ef6f9cba798d891048fa26c7d4ce03015bf8bc7d51fa33175ebbf6f9d5995caac1380c58a3a516bf1a74ccbe0407fb3f9d73f1578b46d3f6cc55e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
